### ISSUE TITLE
Write one line of galah to retrieve the distribution for "Banksia" and "Burnettia" (the plant not the oyster)

### ISSUE THREAD

**Issue by wcornwell** [wcornwell/endemism#1]

**Comment by WeppnerJames** [comment]
I have the code to pull from galah but it's saying there is an error:

Error in parse_url(status$statusUrl) : length(url) == 1 is not TRUE

I'm trying to find how to fix this still but I haven't found anything yet.

**Comment by wcornwell** [comment]
Send like you're close. Post your code

**Comment by WeppnerJames** [comment]
Banksia <- galah_call() |>
  galah_identify("Banksia") |>
  atlas_occurrences()
result |> head()

**Comment by wcornwell** [comment]
This part: 
```
Banksia <- galah_call() |>
galah_identify("Banksia") |>
atlas_occurrences()
```
works for me, i get a download of 149,985 records

**Comment by wcornwell** [comment]
<img width="1247" alt="Screenshot 2023-06-05 at 11 10 00 am" src="https://github.com/wcornwell/endemism/assets/5534161/3aabfc73-b09f-4dfd-b2e4-1f69589403c5">

**Comment by WeppnerJames** [comment]
It must be to do with my computer then

**Comment by WeppnerJames** [comment]
I tried using the uni computers to as I think the problem may be with my Mac but it says that galah doesn't have a version for the version of R that is being used so I'm trying to work out how to use earlier versions.

**Comment by wcornwell** [comment]
try: 
```
install.packages("remotes")
remotes::install_github("AtlasOfLivingAustralia/galah")
```
on either machine.
