### ISSUE TITLE
Type of ecosystem maps

### ISSUE THREAD

**Issue by wcornwell** [wcornwell/endemism#17]
Find the right map of ecosystem 

check https://www.nature.com/articles/s41586-022-05318-4

**Comment by WeppnerJames** [comment]
Are we happy with a raster?

**Comment by wcornwell** [comment]
yeah i think that will be easier to work with

**Comment by WeppnerJames** [comment]
http://environment.gov.au/fed/catalog/search/resource/downloadData.page?uuid=%7B991C36C0-3FEA-4469-8C30-BB56CC2C7772%7D

**Comment by wcornwell** [comment]
data is here: https://www.dropbox.com/s/y6ni1jbtypqdn37/locations_endemic_genera.csv?dl=0

**Comment by wcornwell** [comment]
`terra::extract`

**Comment by wcornwell** [comment]
data for locations: https://www.dropbox.com/scl/fi/8k9w1885qnn1f8ozllxk9/locations_endemic_genera_v2.csv?rlkey=xi8rxkac7r73ha8kj15k0l3mm&dl=0

**Comment by WeppnerJames** [comment]
The data I found is can't be opened in R since the file formats are meant to be used in ArcGIS so I'm trying to find .tif files

**Comment by WeppnerJames** [comment]
Update:
I have tried converting the the raster file from .ovr to .tif in arcgis however, the file becomes 1.5GB and I can't find any other dataset to use that is already a .tif but I think all of them may be that size if it covers all of Australia.
