### ISSUE TITLE
join the australia and NZ and PNG lists and figure out overlap

### ISSUE THREAD

**Issue by wcornwell** [wcornwell/endemism#5]
https://environmentalcomputing.net/data-manipulation/combining-datasets/

**Comment by AndreasBartnitzky** [comment]
library(dplyr)

NZ <- read.csv(file = "Banksia species NZ.csv")
AUS <- read.csv(file = "Banksia species AUS.csv")

Combined <- bind_rows(NZ, AUS)

View (Combined)


 this shows us all the AUS rows that have the same Banksia species in the NZ list

Same_species <- semi_join(AUS, NZ, by = 'species')

View (Same_species)


 this shows Banksia found in AUS and not in NZ

Only_AUS_species <- anti_join(AUS, NZ, by = 'species')

View (Only_AUS_species)
